team <- c('Man City', 'Man Utd', 'Totenham', 'Arsenal', 'Chelsea', 'Newcastle', 'Liverpool', 'Stoke')
home_wins <- c(14, 10, 10, 9, 8, 7, 4, 6)
league_table <- data.frame(team, home_wins)
print(league_table)
print(league_table$team)
print(league_table$team[league_table$home_wins > 8])
print(with(league_table, team[home_wins > 8]))

pts <- c(66, 61, 53, 49, 46, 43, 39, 36)
points <- data.frame(team, pts)
print(points)
league <- merge(league_table, points, by = 'team')
print(league)
with(league, league[order(-pts),])
